name: Java CI with Gradle

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest
    - name: Set up JDK 18
      uses: actions/setup-java@latest
      with:
        java-version: 18
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@latest
      with:
        name: pull-request-build
        path: build/libs/
