name: Java CI with Gradle

concurrency: 
  group: "V4"
  cancel-in-progress: true

on:
  push:
    branches: [ V4 ]
    paths-ignore:
      - '*.md'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: 18
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Remove *-dev.jar
      run: rm ./build/libs/*-dev.jar || true
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "V3"
          prerelease: false
          title: "V4"
          files: |
            ./build/libs/*.jar
